# https://docs.oracle.com/javase/7/docs/api/constant-values.html

MODIFIER_PUBLIC = 1
MODIFIER_PRIVATE = 2
MODIFIER_PROTECTED = 4
MODIFIER_STATIC = 8
MODIFIER_FINAL = 16
MODIFIER_SYNCHRONIZED = 32
MODIFIER_VOLATILE = 64
MODIFIER_TRANSIENT = 128
MODIFIER_NATIVE = 256
MODIFIER_INTERFACE = 512
MODIFIER_ABSTRACT = 1024
MODIFIER_STRICT = 2048
